### ISSUE TITLE
Question: Based on QTY?

### ISSUE THREAD

**Issue by maierb** [tzyganu/stock-filter#1]
Thank you for this BRILLIANT idea. It has often been asked of me about doing this same filter but based on QTY > 0 rather than magento's in_stock (because we accept backorders)

**Comment by tzyganu** [comment]
@maierb  Can you explain how do you see this filter by qty working? Having qty intervals like 0, 1-10, 11-20 and so on? I'm curious.

Anyway...there is a problem for any approach you would have in mind.  
Configurable products don't have qty. But they have an `in_stock` flag.  
Also there is the case of products that don't have stock management. They can be in stock (with unlimited qty) or out of stock.

I don't have any plans at the moment to make a filter by qty mainly because I have no idea on how to tackle it.  
But if you come up with a good idea I might reconsider.

**Comment by tzyganu** [comment]
Closed due to inactivity from the OP.

**Comment by maierb** [comment]
Sorry I didnt see your initial reply, let me review again and get back to you, sorry for that

**Comment by maierb** [comment]
I remember now, some sites I work with request this feature but allow backorders, so products do not trip the flag. So its for use cases where "we do not have it because we have 0" so we want to ship what we have in stock
