### ISSUE TITLE
Layered Nav Position

### ISSUE THREAD

**Issue by shahroq** [tzyganu/stock-filter#3]
Hi,
Is there any way to change the Stock Status Box in layered nav position? i need to put the box above other boxes.

**Comment by tzyganu** [comment]
@shahroq You cannot move the position of the stock status box. I don't remember the reason, but It's some kind of limitation from Magento.  I created [the same extension for Magento 2](https://github.com/tzyganu/magento2-stock-filter) and in that one you can move the block up and down. But that one was made as a proof of concept. It has other bugs.  

I will close this issue for now since is more a question than an issue.

**Comment by shahroq** [comment]
Finally i come of with jQuery solution for do this, for those who wants to do the same:

```
jQuery(document).ready(function($) {
  //stock status to top
  var statusBox = $("#box li:last()");
  $(#box > li:eq(0)').after(statusBox);
});
```

and of course you should change selector to match your theme.
